#!/usr/bin/env python3
"""
Test script for the Cosmos3D postprocessor.
This script validates that the postprocessor works correctly.
"""

import os
import sys
import tempfile
import subprocess
from pathlib import Path

def create_test_gcode():
    """Create a test G-code file."""
    test_content = """
; Test G-code for Cosmos3D postprocessor
; layer_height = 22
; nozzle_diameter = 60
; Generated by OrcaSlicer for testing
G21 ; Set units to millimeters
G90 ; Use absolute coordinates
M82 ; Use absolute distances for extrusion
G92 E0 ; Reset extruder position
;LAYER:0
G1 X100 Y100 Z22 F1500
G1 X200 Y100 E10 F800
G1 X200 Y200 E20 F800
G1 X100 Y200 E30 F800
G1 X100 Y100 E40 F800
;LAYER:1
G1 Z44 F300
G1 X100 Y100 E50 F800
G1 X200 Y100 E60 F800
G1 X200 Y200 E70 F800
G1 X100 Y200 E80 F800
G1 X100 Y100 E90 F800
; End of test file
"""
    
    with tempfile.NamedTemporaryFile(mode='w', suffix='.gcode', delete=False) as f:
        f.write(test_content.strip())
        return f.name

def test_postprocessor():
    """Test the postprocessor functionality."""
    print("Testing Cosmos3D postprocessor...")
    
    # Get script directory
    script_dir = Path(__file__).parent
    postprocessor_path = script_dir / "cosmos3d_postprocessor.py"
    
    if not postprocessor_path.exists():
        print(f"ERROR: Postprocessor script not found at {postprocessor_path}")
        return False
    
    # Create test input
    input_file = create_test_gcode()
    output_file = input_file + ".processed"
    
    try:
        # Set environment variables like Orca Slicer would
        env = os.environ.copy()
        env['SLIC3R_PP_HOST'] = 'File'
        env['SLIC3R_PP_OUTPUT_NAME'] = output_file
        
        # Run postprocessor
        cmd = [sys.executable, str(postprocessor_path), input_file, '-o', output_file]
        result = subprocess.run(cmd, env=env, capture_output=True, text=True)
        
        if result.returncode != 0:
            print(f"ERROR: Postprocessor failed with exit code {result.returncode}")
            print(f"STDERR: {result.stderr}")
            return False
        
        # Check output file exists
        if not os.path.exists(output_file):
            print("ERROR: Output file was not created")
            return False
        
        # Read and validate output
        with open(output_file, 'r') as f:
            processed_content = f.read()
        
        # Check for expected content
        expected_patterns = [
            "; Cosmos3D Concrete Printer G-code",
            "; === CONCRETE PRINTING SAFETY NOTICE ===",
            "M117 Starting concrete print",
            "M117 Printing Layer",
            "M117 Concrete print complete"
        ]
        
        for pattern in expected_patterns:
            if pattern not in processed_content:
                print(f"ERROR: Expected pattern not found: {pattern}")
                return False
        
        print("SUCCESS: All tests passed!")
        print(f"Input file: {input_file}")
        print(f"Output file: {output_file}")
        print(f"Processed content length: {len(processed_content)} characters")
        
        return True
        
    except Exception as e:
        print(f"ERROR: Test failed with exception: {e}")
        return False
    
    finally:
        # Clean up
        for file_path in [input_file, output_file]:
            if os.path.exists(file_path):
                os.unlink(file_path)

if __name__ == "__main__":
    success = test_postprocessor()
    sys.exit(0 if success else 1)